introTitle = "WELCOME TO THIS LOOP PRACTICE"
introSubtext = "IN HERE YOU CAN SEE THE PRACTICE AND ANSWER FOR THE LOOP EXERCISES AND THERE ARE 9 FOR LOOPS AND 4 " \
               "WHILE LOOPS."
choosetext = "PLEASE CHOOSE WHAT KIND OF LOOP PRACTICE YOU WOULD LIKE TO CHECK (WHILE OR FOR) AND END TO QUIT: "
forloop = 'for'
whileloop = 'while'
chosentext = "YOU HAVE CHOSEN"
enterquestionnumbertext = "PLEASE ENTER THE NUMBER QUESTION THAT YOU WOULD LIKE TO SEE:"
thankstext = "THANKS FOR WATCHING"
validtext = "PLEASE ENTER A VALID VALUE"
